version: "3"
services:
  web:
    build: .
    container_name: "web-treinototal-ranks"
    ports:
      - "3405:80"
    stdin_open: true
    tty: true
    # volumes:
    #   - ./:/app
    #   - ./app/node_modules
