version: "3"
services:
  web:
    build: .
    container_name: "web-treinototal-senai"
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    # volumes:
    #   - ./:/app
    #   - ./app/node_modules
